---
title: "Quantitative assignment"
author: "Gayoung"
date: "Wednesday, April 08, 2015"
output: html_document
---

Three potential questions relating with my research question. My research topic is stemmed points and I would like to figure out the driver that let people to make the points and the cause of the changes in stemmed points throughout the Upper Paleolithic in Korea. 

1. How can I connect the theory of evolution and the starting point of new lithics such as stemmed point in the Upper Plaeolitic period.
2. Is there some relationshipe between the extinction of mammals such as mammoth and change of stone tool? If so, I would like to see the transion between phase to phase of stemmed point based on the theory of the extinction.
3. Which attributes on lithic I should choose to figure out the change of lithic according of climate change?

Code

<pre code>
JSTOR_2words(multiple_archives, "Extinction", "stone tool")
JSTOR_2wordcor(multiple_archives, "Extinction", "stone tool")

nouns <-  JSTOR_dtmofnouns(multiple_archives, sparse = 0.75) #create corpus of nouns
JSTOR_freqwords(multiple_archives, nouns)
JSTOR_findassocs(multiple_archives, nouns, "Extinction")
JSTOR_clusterbywords(nouns, 'Extinction')

my_model <- JSTOR_lda(mulitple_archives, nouns, 50) #generate topic model
JSTOR_lda_docdists(my_model)
JSTOR_lda_hotncoldtopics(my_model)
</pre code>